### ISSUE TITLE
The pytorch implementation cannot use gpu to train

### ISSUE THREAD

**Issue by Jackory** [cts198859/deeprl_network#11]
I want to train it on GPU. But I see the code can only train on CPU as default. So I change the parameter: `use_gpu=True` as follows.
![image](https://user-images.githubusercontent.com/52418786/110435902-8c56c280-80ee-11eb-9b8c-8ba61cd118a0.png)
But then, I got this error:
![image](https://user-images.githubusercontent.com/52418786/110436109-c758f600-80ee-11eb-8766-758f63c7e170.png)
So how can I fix this bug? Thank you very much

**Comment by cts198859** [comment]
'gpu' version is not supported as SUMO may cause problems.
