### ISSUE TITLE
why are the reward norm different between different model?

### ISSUE THREAD

**Issue by Wangjw6** [cts198859/deeprl_network#13]
For example,
In config_ia2c_catchup.ini, the reward_norm is 800
while in config_ma2c_dial_catchup.ini, the reward_norm is 5000

**Comment by cts198859** [comment]
Since the original rewards have different scales. ia2c only contains neighborhood rewards while ma2c contains (discounted) global rewards. For fair comparison, we make the normalized rewards at similar scales.

**Comment by Wangjw6** [comment]
> Since the original rewards have different scales. ia2c only contains neighborhood rewards while ma2c contains (discounted) global rewards. For fair comparison, we make the normalized rewards at similar scales.

Thank you for the quick response! So are the normalized rewards only used for training? What about the evaluation after training?

**Comment by cts198859** [comment]
Yes, in evaluation, we always use the original global reward, since this is what we want to optimize.

**Comment by Wangjw6** [comment]
> Yes, in evaluation, we always use the original global reward, since this is what we want to optimize.

Got it. Thank you :)
