### ISSUE TITLE
How is the traffic distribution graph drawn？

### ISSUE THREAD

**Issue by Jackory** [cts198859/deeprl_network#15]
Sorry to bother you, Can you tell me how to draw this graph, I haven't found the source code in the repository.Thank you very much.
![image](https://user-images.githubusercontent.com/52418786/115104857-dfddeb00-9f8d-11eb-94ad-7202e21869fd.png)

**Comment by cts198859** [comment]
They are simply screenshots of SUMO GUI during the evaluation run, after applying [view config]( https://github.com/cts198859/deeprl_network/blob/c279b1fc83ecb7367d38f4a8ada5f3cf585aec59/envs/large_grid_data/view.xml), as mentioned in usage step 4.
