### ISSUE TITLE
FingerPrint algorithm

### ISSUE THREAD

**Issue by wawachen** [cts198859/deeprl_network#16]
hello,

For the FingerPrint, in original paper `Stabilising Experience Replay for Deep Multi-Agent Reinforcement Learning`, it use iteration number and annulling rate as the fingerprint.

but in your code, i cannot recognize which fingerprint you are using, and  it seems you don't update the fingerprint. Could you help to understand that?

**Comment by cts198859** [comment]
Good question! We do update the fingerprints after each episode: https://github.com/cts198859/deeprl_network/blob/c279b1fc83ecb7367d38f4a8ada5f3cf585aec59/envs/atsc_env.py#L212.

The definition of fingerprint is different: the original paper evaluates off-policy learning so it uses iteration number etc to reflect the agent behavior. A2C is on-policy learning so we directly use policy to represent the neighbor's behavior.
